# Required
version: 2

build:
  image: latest

# Python version and build requirements
python:
  version: 3.8
  system_packages: true
  install:
    - requirements: docs/requirements.txt
    - method: setuptools
      path: .
