name: qimpy
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pyyaml
  - pytorch
  - psutil
  - numpy
  - h5py
  - mpi4py
  - scipy
  - svg.path
  - typing-extensions
  - sphinx_rtd_theme
